config/routes.rb
Rails.application.routes.draw do
	root 'static_pages#home'
	get  '/signup',  to: 'users#new'
	post '/signup', to: 'users#create'
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'
	
	resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	before_save {self.email.downcase!}
	validates :name, presence: true, length: {maximum: 50}
	VALIDATE_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255},
					  format: {with: VALIDATE_EMAIL_REGEX},
					  uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, presence: true, length: {minimum: 6}, allow_nil: true

	# Returns the hash digest of the given string.
	def self.digest string
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# Returns a random token.
	def self.new_token
		SecureRandom.urlsafe_base64
	end

	# Search users
	def self.search name
		User.where("name like ?", "%#{name}%")
	end

	# Remembers a user in the database for use in persistent sessions.
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	# Returns true if the given token matches the digest.
	def authenticated? remember_token
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	# Forgets a user.
	def forget
		update_attribute(:remember_digest, nil)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper

	private
	# Confirms a logged-in user.
		def logged_in_user
			unless logged_in?
				store_location
				flash[:danger] = "Please log in"
				redirect_to login_url
			end
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			log_in user
			params[:session][:remember_me] == "1" ? remember(user) : forget(user)
			redirect_back_or user
		else
			@error = "Invalid email or password"
			render 'new'
		end
	end

	def destroy
		log_out if logged_in?
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			redirect_to @user
		else
			render 'new'
		end
	end

	def index
	end

	def show
		@user = User.find(params[:id])
	end

	private
		def user_params
			params.require(:user).permit(:name, :email, :gender, :password,
										 :password_confirmation, :avatar)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title page_title = ''
		base_title = "Photogram"
		if page_title.empty?
			base_title
		else
			page_title
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Logs in the given user
	def log_in user
		session[:user_id] = user.id
		# create a temporary cookie with encrypted id
	end

	# Remembers a user in a persistent session.
	def remember user
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	# Returns true if given user is the current user
	def current_user? user
		current_user == user
	end

	# Returns the current logged-in user (if any)
	def current_user
		if user_id = session[:user_id]
			@current_user ||= User.find_by(id: user_id)
		elsif user_id = cookies.signed[:user_id]
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end

	# Returns true if user is logged in, false in otherwise
	def logged_in?
		!current_user.nil?
	end

	# Forgets a persistent session.
	def forget user
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	# Logs out the current user.
	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

	# Redirects to stored location (or to the default).
	def redirect_back_or default
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end

	# Stores the URL trying to be accessed.
	def store_location
		session[:forwarding_url] = request.original_url if request.get?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav>
	<div class="nav-wrapper">
		<a href="/" class="brand-logo"><%= fa_icon "instagram" %> | Photogram</a>
		<% if logged_in? %>
			<%= form_tag users_path, method: "get", class: "users-search" do %>
				<%= text_field_tag :search, params[:search], class: "search-box", placeholder: "Search..." %>
			<% end %>
		<% end %>
		<ul id="nav-mobile" class="right hide-on-med-and-down">
			<% if logged_in? %>
				<li class="dropdown">
					<a href="#" charset="dropdown-toggle" data-toggle="dropdown">
						<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
					</a>
					<ul class="dropdown-menu notifi-dropdown">
						<li>Notifications</li>
					</ul>
				</li>
				<li>
					<%= link_to current_user do %>
						<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
					<% end %>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to "Settings", edit_user_path(current_user) %></li>
						<li><%= link_to "Log out", logout_path, method: "delete" %></li>
					</ul>
				</li>
			<% else %>
				<% if current_page?(root_path) %>
					<li><a href="#about-path" onclick="internal_link_click(this)">About</a></li>
					<li><a href="#portfolio-path" onclick="internal_link_click(this)">Portfolio</a></li>
					<li><a href="/login">Sign In</a></li>
				<% end %>
			<% end %>
		</ul>
	</div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Photogram</title>
		<%= render "layouts/rails_default" %>
		<%= render "layouts/shim" %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>"><%= message %></div>
		<% end %>
		<%= yield %>
	</body>
</html>

app/views/static_pages/home.html.erb
<% if !logged_in? %>
	<div class="content">
		<div class="jumbotron">
			<div class="caption">
				<h2>Slick Material Design</h2>
				<h4>Image Social Network</h4>	
				<%= link_to "Let's enjoy", signup_path, class: "waves-effect waves-light btn" %>
			</div>
		</div>
		<div class="container present">
			<div class="overview">
				<div class="introductory">
					Nullam blandit gravida viverra. Etiam turpis erat, sagittis sit amet felis non, porta porta justo. Integer ornare nibh nulla, id pulvinar metus cursus semper. Vivamus dictum pellentesque mi. Vivamus ipsum tellus, mattis non ex sed, semper sodales ligula. Vivamus luctus lorem.
				</div>
				<div class="features">
					<div class="feature">
						<%= fa_icon "th" %>
						<div class="caption">
							<div class="title">Responsive</div>
							Lorem ipsum dolor sit amet elit do, consectetur adipiscing, sed eiusmod tempor incididunt ut labore et dolore magna aliqua.
						</div>
					</div>
					<div class="feature">
						<%= fa_icon "th-list" %>
						<div class="caption">
							<div class="title">Quality</div>
							Lorem ipsum dolor sit amet elit do, consectetur adipiscing, sed eiusmod tempor incididunt ut labore et dolore magna aliqua.
						</div>
					</div>
					<div class="feature">
						<%= fa_icon "reorder" %>
						<div class="caption">
							<div class="title">Support</div>
							Lorem ipsum dolor sit amet elit do, consectetur adipiscing, sed eiusmod tempor incididunt ut labore et dolore magna aliqua.
						</div>
					</div>
				</div>
			</div>
			<div class="about" id="about-path">
				<div class="row">
					<div class="about-caption col-md-4">
						<h2>Who are we now</h2>
						<p>THE STORY THAT MADE US WHO WE ARE</p>
						<p>Ideate integrate food-truck agile ideate thinker-maker-doer user story intuitive hacker integrate workflow Steve Jobs. Steve Jobs pair programming food-truck big data long shadow SpaceTeam agile agile affordances. User centered design food-truck experiential minimum viable product human-centered design prototype viral quantitative vs. qualitative.</p>
					</div>
					<div class="about-image col-md-8">
						<img src="/assets/about.png">
					</div>
				</div>
			</div>
			<div class="portfolio" id="portfolio-path">
				<div class="overview">
					<div class="title">Portfolio</div>
					<div class="caption">
						Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
					</div>
				</div>
				<div class="row">
					<div class="item col-md-4">
						<div class="portfolio-pic" id="portfolio-1">
							<div class="portfolio-content">
								<span class="label label-primary">productivity</span>
								<div class="portfolio-title">Morbi mauris diam</div>
							</div>
						</div>	
					</div>
					<div class="item col-md-4">
						<div class="portfolio-pic" id="portfolio-2">
							<div class="portfolio-content">
								<span class="label label-info">design</span>
								<div class="portfolio-title">Interdum et malesuada</div>
							</div>
						</div>	
					</div>
					<div class="item col-md-4">
						<div class="portfolio-pic" id="portfolio-3">
							<div class="portfolio-content">
								<span class="label label-danger">productivity</span>
								<div class="portfolio-title">Duis laoreet tellus arcu</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="item col-md-6">
						<div class="portfolio-pic" id="portfolio-4">
							<div class="portfolio-content">
								<span class="label label-warning">productivity</span>
								<div class="portfolio-title">Proin aliquet nibh varius</div>
							</div>
						</div>	
					</div>
					<div class="item col-md-6">
						<div class="portfolio-pic" id="portfolio-5">
							<div class="portfolio-content">
								<span class="label label-primary">productivity</span>
								<div class="portfolio-title">Our Awesome Project</div>
							</div>
						</div>	
					</div>
				</div>
				<div class="row">
					<div class="item col-md-4">
						<div class="portfolio-pic" id="portfolio-6">
							<div class="portfolio-content">
								<span class="label label-success">design</span>
								<div class="portfolio-title">Up branch to easily missed</div>
							</div>
						</div>	
					</div>
					<div class="item col-md-4">
						<div class="portfolio-pic" id="portfolio-7">
							<div class="portfolio-content">
								<span class="label label-primary">design</span>
								<div class="portfolio-title">Boy favourable day</div>
							</div>
						</div>	
					</div>
					<div class="item col-md-4">
						<div class="portfolio-pic" id="portfolio-8">
							<div class="portfolio-content">
								<span class="label label-info">productivity</span>
								<div class="portfolio-title">Bringing unlocked me</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<footer class="page-footer">
		<div class="container">
			<div class="row">
				<div class="col-md-10">
					<p class="title">Get in Touch</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
				</div>
				<div class="col-md-2">
					<p class="title">Find Us At</p>
					<p><%= fa_icon "map-marker" %> Hanoi, Vietnam</p>
					<p><%= fa_icon "mobile" %> +84123456789</p>
				</div>
			</div>
		</div>
		<div class="footer-copyright">
			<div class="container">
				<div class="row">
					<div class="col-md-10">© 2017 Copyright Text</div>
					<div class="col-md-2">Created by anhtthust</div>
				</div>
			</div>
		</div>
	</footer>
<% else %>
	<div class="main-content">
		<%= render 'static_pages/home_left_block' %>
		<%= render 'static_pages/home_center_block' %>
		<%= render 'static_pages/home_right_block' %>
	</div>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div id="login-box">
	<div class="left-block">
		<h1>Sign up</h1>
		<%= form_for(@user, url: signup_path) do |f| %>
			<% if @user.errors[:name].length != 0 %>
				<div class="error-messages"><%= @user.errors[:name][0] %></div>
			<% end %>
			<%= f.text_field :name, placeholder: "Harry Potter 90", class: "form-control" %>

			<% if @user.errors[:email].length != 0 %>
				<div class="error-messages"><%= @user.errors[:email][0] %></div>
			<% end %>
			<%= f.email_field :email, placeholder: "harry@gmail.com", class: "form-control" %>

			<% if @user.errors[:password].length != 0 %>
				<div class="error-messages"><%= @user.errors[:password][0] %></div>
			<% end %>
			<%= f.password_field :password, placeholder: "Password", class: "form-control" %>

			<% if @user.errors[:password_confirmation].length != 0 %>
				<div class="error-messages"><%= @user.errors[:password_confirmation][0] %></div>
			<% end %>
			<%= f.password_field :password_confirmation, placeholder: "Password Confirmation", class: "form-control" %>

			<%= f.radio_button :gender, "Male", checked: true, id: "male-radio" %>
			<%= f.label :gender, "Male", for: "male-radio" %>
			<%= f.radio_button :gender, "Female", checked: false, id: "female-radio" %>
			<%= f.label :gender, "Female", for: "female-radio" %>
			<br>
			<%= f.submit "Enjoy With Us !" %>
		<% end %>
		<br>
		<p>Already had account? <%= link_to "Let's go", login_path %></p>
	</div>
	<div class="right-block">
		<span class="login-with">Sign in with<br>social network</span>
		<button class="social-signin facebook">Log in with facebook</button>
		<button class="social-signin google">Log in with Google+</button>
	</div>
	<div class="or">OR</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container user-profile">
	<br><br>
	<div class="row">
		<div class="col-xs-4">
			<div class="avatar">
				
			</div>
		</div>
		<div class="col-xs-8">
			<div class="name-express">
				<div class="name"><%= @user.name %></div>
				<div class="config-area">
					<% if current_user?(@user) %>
						<%= link_to "Edit Profile", edit_user_path(current_user), id: "edit-profile-btn" %>
					<% else %>
						<% if @user.admin? == false %>
							<%= render 'follow_form' if logged_in? %>
						<% end %>
					<% end %>
				</div>
			</div>
			<div class="user-info-express">
				
			</div>
		</div>
	</div>
</div>